# Generated by Django 2.2.13 on 2021-05-08 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OxygenOrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_cylinder', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True, default='', null=True)),
                ('status', models.BooleanField(default=False)),
                ('oxygensupplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oxygensupplier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
