# Generated by Django 2.2.13 on 2021-05-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctormodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
