# Generated by Django 2.2.13 on 2021-05-03 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0004_auto_20210503_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='OxygenOrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True, default='', null=True)),
                ('status', models.BooleanField(default=False)),
                ('oxygenhospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oxygenhospital', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
