# Generated by Django 2.2.13 on 2021-05-03 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0005_oxygenordermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodOrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodtype', models.IntegerField(blank=True, choices=[(1, 'A+'), (2, 'A-'), (3, 'B+'), (4, 'B-'), (5, 'AB+'), (6, 'AB-'), (7, 'O+'), (8, 'O-')], null=True)),
                ('required', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True, default='', null=True)),
                ('status', models.BooleanField(default=False)),
                ('bloodhospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloodhospital', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
