# Generated by Django 2.2.13 on 2021-05-03 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0007_auto_20210503_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaitentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paitentstatus', models.CharField(blank=True, choices=[('RECOVERED', 'RECOVERED'), ('ONHOLD', 'ONHOLD'), ('PURSUING', 'PURSUING'), ('RECOVERED', 'RECOVERED')], max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('disease', models.TextField(blank=True, default='', null=True)),
                ('oxygenstatus', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='hospital.DoctorModel')),
                ('paitenthospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paitenthospital', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='hospital.RoomModel')),
            ],
        ),
    ]
