# Generated by Django 2.2.13 on 2021-05-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_paitentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paitentmodel',
            name='paitentstatus',
            field=models.CharField(blank=True, choices=[('ADMISSION', 'ADMISSION'), ('ONHOLD', 'ONHOLD'), ('PURSUING', 'PURSUING'), ('RECOVERED', 'RECOVERED')], max_length=20, null=True),
        ),
    ]
