# Generated by Django 2.2.13 on 2021-05-18 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0009_auto_20210505_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambtype', models.CharField(blank=True, choices=[('ICU', 'ICU'), ('OXYGEN', 'OXYGEN'), ('GENERAL', 'GENERAL'), ('COVID', 'COVID')], max_length=20, null=True)),
                ('drivername', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('ambhospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambhospital', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
