# Generated by Django 2.2.13 on 2021-05-20 12:25

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_ambulance'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AlterField(
            model_name='roommodel',
            name='room_type',
            field=models.CharField(choices=[('COVID', 'COVID'), ('GENERAL', 'GENERAL')], default='COVID', max_length=10),
        ),
    ]
